#!/usr/bin/env bash
./run.sh basic_example
./run.sh init                         
./run.sh reservoir_sampling         
./run.sh bloomfilter   
./run.sh monotone_binary_search    
./run.sh reservoir_sampling_syminput
./run.sh countminsketch     
./run.sh montyhall     
./run.sh schwartz_zippel            
./run.sh fisher_yates_sampler    
./run.sh partition     
./run.sh skiplist                   
./run.sh freivalds  
./run.sh quicksort    
./run.sh zp_hash                    
./run.sh freivalds_multiple      
./run.sh randomized_response                                         